/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PastEventRouteImport } from './routes/past-event'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as Register2RouteImport } from './routes/register2'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PastEventRoute = PastEventRouteImport.update({
  id: '/past-event',
  path: '/past-event',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const Register2Route = Register2RouteImport.update({
  id: '/register2',
  path: '/register2',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/partner': typeof PartnerRoute
  '/past-event': typeof PastEventRoute
  '/register': typeof RegisterRoute
  '/register2': typeof Register2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/partner': typeof PartnerRoute
  '/past-event': typeof PastEventRoute
  '/register': typeof RegisterRoute
  '/register2': typeof Register2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/partner': typeof PartnerRoute
  '/past-event': typeof PastEventRoute
  '/register': typeof RegisterRoute
  '/register2': typeof Register2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/partner' | '/past-event' | '/register' | '/register2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/partner' | '/past-event' | '/register' | '/register2'
  id: '__root__' | '/' | '/partner' | '/past-event' | '/register' | '/register2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PartnerRoute: typeof PartnerRoute
  PastEventRoute: typeof PastEventRoute
  RegisterRoute: typeof RegisterRoute
  Register2Route: typeof Register2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-event': {
      id: '/past-event'
      path: '/past-event'
      fullPath: '/past-event'
      preLoaderRoute: typeof PastEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register2': {
      id: '/register2'
      path: '/register2'
      fullPath: '/register2'
      preLoaderRoute: typeof Register2RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PartnerRoute: PartnerRoute,
  PastEventRoute: PastEventRoute,
  RegisterRoute: RegisterRoute,
  Register2Route: Register2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
